
Test Suite	Test Case	Description	Priority	Test Type	Frequency	Handling Dynamic Data
Price Accuracy Test Suite	Flight Price Display	Verify flight price ($20.00) matches backend data.	High	Automated Functional	With every build, nightly	Mock API responses for price data.
Price Accuracy Test Suite	Coverage Option Price Display	Validate that the price for 'Premium Disruption Assistance' ($100) is correct.	High	Automated Functional	With every build, nightly	Use stubs for coverage option prices.
Price Accuracy Test Suite	Taxes and Fees Display	Ensure that taxes and fees ($15) are correctly displayed.	High	Automated Functional	With every build, nightly	Mock API responses for taxes and fees.
Price Accuracy Test Suite	Total Price Calculation	Check that the total price ($115) is calculated correctly.	High	Automated Functional	With every build, nightly	Validate calculations using mock data for all price components.
Price Accuracy Test Suite	Dynamic Pricing Update	Verify that changing coverage options updates the total price accurately.	High	Automated Functional	With every build, nightly	Mock dynamic price updates and validate calculations.
Interactive Elements Test Suite	Button Functionality	Verify that buttons ('Sign in,' 'Continue,' 'No, thanks') function correctly.	High	Automated and Manual Functional	Automated daily, manual during major updates	Use parameterized tests to validate button actions.
Interactive Elements Test Suite	Dropdown Functionality	Ensure that the language dropdown ('English▾') functions correctly.	High	Automated and Manual Functional	Automated daily, manual during major updates	Use mock data for dropdown options; validate functionality.
Interactive Elements Test Suite	Link Navigation	Verify that links ('How it works,' 'View Terms') navigate to the correct pages.	High	Automated and Manual Functional	Automated daily, manual during major updates	Use mock URLs; validate link navigation.
Error Handling and Edge Case Test Suite	Error Messaging	Verify that error messages are displayed for scenarios such as network failures or invalid data inputs.	Medium	Automated and Manual	With every build, weekly	Mock error scenarios; validate error message display.
Error Handling and Edge Case Test Suite	Edge Case Handling	Test edge cases such as maximum number of travelers or extreme price values.	Medium	Automated and Manual	With every build, weekly	Use parameterized tests to simulate edge cases; validate handling.
Performance Test Suite	Page Load Time	Measure the time it takes for the offer screen to load completely.	Medium	Automated Performance	With every build, nightly	Simulate dynamic data load; measure performance with varying data volumes.
Performance Test Suite	Interactive Response Time	Check the response time of interactive elements (buttons, dropdowns).	Medium	Automated Performance	With every build, nightly	Use mock data to simulate user interactions; measure response times.
Performance Test Suite	Stress Testing	Perform stress testing to ensure the page performs well under heavy load.	Medium	Automated Performance	With every build, nightly	Simulate high traffic scenarios using load testing tools.
UI and Layout Test Suite	Static Element Display	Verify static elements (e.g., 'hopper,' 'Company,' etc.) are displayed correctly.	Medium	Manual and Automated Visual	Automated daily, manual during major updates	Use reference images for comparison.
UI and Layout Test Suite	Dynamic Element Display	Check dynamic elements (prices, totals) are correctly displayed and formatted.	Medium	Manual and Automated Visual	Automated daily, manual during major updates	Mock dynamic data for consistency.
UI and Layout Test Suite	Cross-Browser Display Consistency	Ensure all elements are displayed consistently across different browsers using Sauce Labs.	Medium	Automated Visual	Automated daily	Use Sauce Labs for cross-browser testing.
UI and Layout Test Suite	Cross-Device Display Consistency	Ensure all elements are displayed consistently across different devices using Sauce Labs.	Medium	Automated Visual	Automated daily	Use Sauce Labs for cross-device testing.
